export const timeZoneOffsets = {
	"Iran / Tehran": 3.5,
	"Moscow / Russia": 3,
	"Turkey / Istanbul": 3,
	"Germany / Berlin": 2,
	"France / Paris": 2,
	"UK / London": 1,
	"USA / New York": -4,
	"USA / Los Angeles": -7,
	"USA / Chicago": -5,
	"USA / Denver": -6,
	"USA / Phoenix": -7,
	"USA / Anchorage": -8,
	"USA / Honolulu": -10,
	"Japan / Tokyo": 9,
	"China / Beijing": 8,
	"India / New Delhi": 5.5,
	"Australia / Sydney": 10,
	"New Zealand / Wellington": 12,
	"Canada / Vancouver": -7,
	"Canada / Toronto": -4,
	"Canada / Halifax": -3,
};
